### ISSUE TITLE
How to include one macro in another macro from different twig file?

### ISSUE THREAD

**Issue by leotankilevich** [yiisoft/yii2-twig#111]
I have two macros One for button and one for spinner. If i try to import spinner macro in button macro and call button macron in view it cause this error; Is there properly way to use macro in macro?
![photo_2018-12-25_14-43-16](https://user-images.githubusercontent.com/16896650/50421705-71703e80-0853-11e9-90c6-13af98aada57.jpg)

**Comment by schmunk42** [comment]
Can you post your twig templates?
