### ISSUE TITLE
Incompatible with Twig 2.7.2

### ISSUE THREAD

**Issue by nnrudakov** [yiisoft/yii2-twig#115]
Update composer. I have `Admin` model with string `role` attribute. I have an empty model in create form. My template fragment:
```twig
{% if model.role != constant('app\\models\\Admin::ROLE_SUPERADMIN') %}
    {{ form.field(model, 'role').dropDownList(roles)|raw }}
{% endif %}
```
And in condition I've got an error:
```
Twig\Error\RuntimeError
An exception has been thrown during the rendering of a template ("Calling unknown method: app\models\Admin::role()").
↵
Caused by: Unknown Method – yii\base\UnknownMethodException
```
It works with Twig 2.6.2.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version      | 2.0.16.1
| Yii Twig version | 2.2.1
| Twig version     | 2.7.2
| PHP version      | 7.0+
| Operating system | Ubuntu

**Comment by machour** [comment]
Confirmed, it seems that our tests broke with Twig 2.7.0.
It might have something to do with the security fix to the sandbox: https://github.com/twigphp/Twig/blob/2.x/CHANGELOG#L75

**Comment by nnrudakov** [comment]
It works well with Yii 2.0.19 and Twig 2.11.1.

**Comment by nnrudakov** [comment]
Error appears when environment option `strict_variables` is `true`. Twig trying call a method if property is `null`. There is no error if `strict_variables` is `false`. Checked on Twig v2.12.1 also.
