### ISSUE TITLE
twig and i18n

### ISSUE THREAD

**Issue by rauwebieten** [yiisoft/yii2-twig#116]
How can I translate messages in twig templates? It seems there is not function/filter defined.

I can use `{{ app.i18n.translate('app','First name',{},'nl-BE') }}`
But is there a shortcut like Yii::t ?

Also, can the cli-command for extracting messages find these messages?

**Comment by samdark** [comment]
Cli command can not find these. Likely it could be adjusted for it but I haven't looked into it. Also there's no shortcut for `t()`.

**Comment by rauwebieten** [comment]
A shortcut is easily added in the twig config:
```
...
'functions' => [
    't' => [\Yii::class,'t']
]
...
```
Also, when my twig templates are compiled into the cache directories, the extractor can find them now by parsing the compiled .php files.

**Comment by samdark** [comment]
Oh, cool. `t()` could be implemented by default and pointing extraction to compiled templates could be documented.

**Comment by developedsoftware** [comment]
Sorry to comment on a closed issue, but this does not appear to be picked up by 

console/controllers/MessageController.php

Can Yii.t or t( calls in twig files be "extracted" like Yii::t in PHP files?
