### ISSUE TITLE
using set to set the page title does not work

### ISSUE THREAD

**Issue by boultra** [yiisoft/yii2-twig#12]
l have a layout named `v1.twig`
 ```twig
<html>
<head>
<title>{{ this.title|e}}</title>
</head>
<body>
{% block content %}
{# content placeholder #}
{% endblock content %}
</body>
</html>
```

When I want to render a view,I write a `index.twig` file like this:
```twig
{% extends 'layouts/v1.twig' %}
{% block content %}
{{ set(this,'title','titleName') }}
my content
{% endblock content %}
```
but the title was not changeed when the page rendered.
I think maybe this problem caused by the render order,it will render the layout `v1.twig' first and then `index.twig`,when it renders v1.twig,it can not get the value of title set in the `index.twig`,how can solve this problem or any other advice?

**Comment by jneto81** [comment]
hello, i'm new with twig but i think in order to work, you have something like

```
{% extends 'layouts/v1.twig' %}

{% block mytitle %}
{{ set(this,'title','titleName') }}
{% endblock mytitle %}

{% block content %}
my content
{% endblock content %}
```
and in v1.twig

```
<html>
<head>

<title>
{% block mytitle %}
{{ this.title|e}}
{% endblock mytitle %}
</title>

</head>
<body>
{% block content %}
{# content placeholder #}
{% endblock content %}
</body>
</html>
```

**Comment by boultra** [comment]
thanks,I use `block` to solved it as you mentioned before,It works!

**Comment by degibons** [comment]
You forgot to add `{{ parent() }}`:
```
{% block mytitle %}
{{ set(this,'title','titleName') }}
{{ parent() }}
{% endblock mytitle %}
```
