### ISSUE TITLE
Is there any other way use static classes in twig file without adding globals?

### ISSUE THREAD

**Issue by odilov-sh** [yiisoft/yii2-twig#127]
### Additional info

| Q                | A
| ---------------- | ---
| Yii version      |
| Yii Twig version |
| Twig version     |
| PHP version      |
| Operating system |

**Comment by odilov-sh** [comment]
It is just difficult add all classes in project to globals?  I want to use any class in twig files. Is there any way use classes?

**Comment by samdark** [comment]
No, there currently isn't.

**Comment by schmunk42** [comment]
> It is just difficult to add all classes within project to globals? I want to use any class in twig files. Is there any way use classes?

I think this is a security feature, you need to whitelist what you want.

You could write one Helper class which does the allowed static calls for you.
