### ISSUE TITLE
Improve exceptions

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-twig#25]
Brandon Kelly shown a way to display template code in exceptions instead of some PHP stuff we have currently: https://gist.github.com/brandonkelly/ee78177a88cd34aa9170

It needs to be wired somehow into the app so when Twig extension is installed, error handler is replaced with Twig's that inherits from default one but could handle templates.

**Comment by amarox** [comment]
@samdark today in exception there are template code (first element of trace)

**Comment by amarox** [comment]
Twig does not catch php errors. But some errors occurs in code that generated by twig. For such errors i added in trace twig template
