### ISSUE TITLE
replacement controller view path

### ISSUE THREAD

**Issue by 4irik** [yiisoft/yii2-twig#31]
Hello!

I'm create widget:

``` php
<?php
namespace frontend\widgets;

use yii\base\Widget;

class SomeWidget extends Widget 
{
    public function run() 
    {
        $this->render('some.twig');
    }
}
```

and used it:

``` twig
{* /frontend/controllers/SiteController::index() *}

{{ use('frontend/widgets/SomeWidget') }}
{{ SomeWidget_widget({}) }}

{{ include('_experts.twig', {selections: selections}) }}
```

and receive error:

`Unable to find template "_experts.twig" (looked into: /var/www/html/frontend/widgets/views) in "index.twig" at line 446.`

PS. sorry for my english (google.translate helped me)

**Comment by amarox** [comment]
Don't confirm this error. Can you show your config file?
