### ISSUE TITLE
Globals - only static classes and objects?

### ISSUE THREAD

**Issue by summerknight** [yiisoft/yii2-twig#34]
Related to [official documentation](http://www.yiiframework.com/doc-2.0/yii-twig-viewrenderer.html#$globals-detail). Public property `globals` allows only static classes and objects. But related to [guide](https://github.com/yiisoft/yii2-twig/blob/master/docs/guide/additional-configuration.md#globals):

`You can define both Yii helpers and your own variables there:`

``` php
'globals' => [
    'html' => '\yii\helpers\Html',
    'name' => 'Carsten',
    'GridView' => '\yii\grid\GridView',
],
```

I tried to use 'name' => 'Carsten' and an exception is occurred (when using `{{name}}` inside template):
`Object of class yii\twig\ViewRendererStaticClassProxy could not be converted to string`

So is it possible to determine global string variable?

**Comment by Lucups** [comment]
I spent more than 1 hour on it. Finally I find this issue...


![image](https://cloud.githubusercontent.com/assets/2325891/22518300/144d8df8-e8e7-11e6-8bfb-b80cae03ee87.png)

**Comment by samdark** [comment]
@Lucups any ideas for a fix?
