### ISSUE TITLE
Getting return value from register_asset_bundle

### ISSUE THREAD

**Issue by alexjeen** [yiisoft/yii2-twig#40]
Sometimes it can be handy to get the return value of register_asset_bundle.

I've tried with:

    {% set bundle = register_asset_bundle('frontend/themes/theme/assets/ThemeAsset') %}

And then for instance to get the property baseUrl of this AssetBundle, but when I do: {{ bundle.baseUrl }} further down it's just an empty string.

In method registerAssetBundle a simple "return" would be enough. I won't create a pull request for such a small thing :)

**Comment by samdark** [comment]
It's not that small thing. It needs tests as well.

**Comment by samdark** [comment]
Done.

**Comment by gta4kv** [comment]
After this 'fix':

    {{ register_asset_bundle('backend/assets/AppAsset') }}

Throws 'Object of class backend\assets\AppAsset could not be converted to string'

And only like this 
    {% set test = register_asset_bundle('backend/assets/AppAsset') %}

works fine

**Comment by alexjeen** [comment]
This is indeed true because {{ expects the value to be echoed. So it tries to echo the AppAsset and fails.

This will work:

     {{ void(register_asset_bundle('backend/assets/AppAsset')) }}

Maybe for backwards compatibility we should introduce a new method (for instance): return_register_asset_bundle. And keep the old method the same.

**Comment by samdark** [comment]
Hmm, that's bad.

**Comment by samdark** [comment]
Reveted my changes/
