### ISSUE TITLE
Using composer, recurrent problem in the component update

### ISSUE THREAD

**Issue by lukBarros** [yiisoft/yii2-twig#42]
Hi mans.

In my workspace, in run composer update, every cases, it fail in the twing update version.

This problem is 'uncommited changes'.

I dont manual change files in the folder vendors, the composer is controller for the vendor folder.

Its is know? recurruent issue (i dont track it)....

**Comment by samdark** [comment]
It's not happening normally and it's not likely Yii issue. Anyway, can't help since can't reproduce it.
