### ISSUE TITLE
closed issues like #40 are not released

### ISSUE THREAD

**Issue by bubasuma** [yiisoft/yii2-twig#44]
issue #40 is not in released versions. I am using in my `composer.json`
```
"yiisoft/yii2-twig": "~2.0.0"
```
but issue #40 is always here. That's why i submitted yesterday issue #43.
Maybe i supposed to use this
```
"yiisoft/yii2-twig": "dev-master"
```
is it secure `dev-master`?

**Comment by SilverFire** [comment]
Of course you can do it, but notice, that changes in master branch are not always stable.

Please note, that GitHub is for bug reports. Asked question is common and can be easily googled.
