### ISSUE TITLE
path() and url() with route without params

### ISSUE THREAD

**Issue by quantum13** [yiisoft/yii2-twig#45]
Hello.

With using `path('/mycontroller/myaction')` if url rule `'GET mypath' => 'mycontroller/myaction'` was defined expected result is `/mypath`, but now it equals  to `/mycontroller/myaction`.

But `path('/mycontroller/myaction', {'myparam':123})` equals to `/mypath?myparam=123`

It is important when `enableStrictParsing` option of `urlManager` was set.

I think `path` and `url` tags must have same syntax as `Url::to`, eg if first params is an array then it should be parsed as route, if string then as custom path.

see PR

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-twig/pull/46

**Comment by samdark** [comment]
Merged https://github.com/yiisoft/yii2-twig/commit/37c0e3952059ea895d88b92967415513e44f88b0. Thanks!
