### ISSUE TITLE
Documentation in README.md is wrong

### ISSUE THREAD

**Issue by cronfy** [yiisoft/yii2-twig#50]
Documentation in [README.md] (https://github.com/yiisoft/yii2-twig/blob/master/README.md) is wrong. 

 It has incorrect configuration example in Usage section.There is no 'globals' option in this example, and without this option 'html' variable does not  work in templates (i. e. {{ html.csrfMetaTags }} does not work).

**Comment by samdark** [comment]
Could you send a pull request correcting it? Thanks!
