### ISSUE TITLE
Error with includes using twig templates in yii2 modules

### ISSUE THREAD

**Issue by jmmerino** [yiisoft/yii2-twig#52]
I'm trying to use twig templates withing a module of yii, but I have problems with the base templates path. I can explain the error better with an example: 

I have a module. Then I'm loading this module in my main app. 

In the module templates, I have some "partials". So, For example, I have "index.twig" and "_header.twig". In the template "index.twig" I want to render the partial "header.twig"

The directory of the module looks like this:
```
modules
- mymoduleid
- - controllers
- - views 
- - - index.twig
- - - _header.twig
```

This is the file "index.twig"
```
...
{% include "_header.twig" %}
...
```

When I try to render that template, I'm getting an error beacuse twig can't find that template. 

In the other hand, If I try to do this render with php templates, it works like a charm:

```
...
<?= $this->render('_form.twig') ?>
...
```

The TwigRenderer is trying to find the partial in the "app" path, instead of in the "module" path... 

Any ideas?

Thanks!

**Comment by rauwebieten** [comment]
How did you fix this?
