### ISSUE TITLE
Wrong documentation additional-configuration.md - Functions

### ISSUE THREAD

**Issue by itnelo** [yiisoft/yii2-twig#54]
Guide https://github.com/yiisoft/yii2-twig/blob/master/docs/guide/additional-configuration.md#functions says: 

```
You can define additional functions like the following:

'functions' => [
    ...
    'sum' => function ($a, $b) {
        return $a + $b;
    }
],
```

But I tried it and got exception:

`Incorrect options for "Function" sum.`
https://github.com/yiisoft/yii2-twig/blob/master/ViewRenderer.php#L254

I'm doing something wrong or there is an actual typo? 
Or case 'is_callable' (or similar) just wasn't implemented?

```
$ composer info -i | grep 'twig'
twig/twig                           v1.24.0            Twig, the flexible, fast, and secure template language for PHP
yiisoft/yii2-twig                   2.0.4              The Twig integration for the Yii framework
```

**Comment by summerknight** [comment]
Maybe related? https://github.com/yiisoft/yii2-twig/issues/34

**Comment by ComradePashka** [comment]
I've tried config below:
```
'functions' => [
  'twig_json_decode' => 'json_decode',
  new \Twig_SimpleFunction('twig_json_decode2', function ($json) {
    return json_decode($json, true);
  }),
  'twig_json_decode3' => function ($json) {
    return json_decode($json, true);
  }
]
```
an `twig_json_decode3` raises an exception `Incorrect options for "Function" twig_json_decode3.` even when never used in twig templates. but first and second config works fine. so for complex custom function we have at least Twig_SimpleFunction.

**Comment by amarox** [comment]
Don't confirm the bug. Are you sure that you try correct you function in template?.

```twig
{{ twig_json_decode3(json) }}
```
