### ISSUE TITLE
Problem with Include helper

### ISSUE THREAD

**Issue by seisvalt** [yiisoft/yii2-twig#55]
Hi, dear Yii2 developers!

I am facing a weird issue with Yii2, Twig and ArrayHelper.

My model hardware has a method devices that returns an array of Device object

So I have this in my view

                   {{ use ('yii/helpers/ArrayHelper') }}  
                   {#I also try use ('yii\helpers\ArrayHelper')#}
                   {{ dump (ArrayHelper.map(devices, 'id', 'name')) }}

That returns: NULL

The only way I can have this working is defining a global in my Twig section's config file this way:

                    'globals' => [
                        'array_helper' => '\yii\helpers\ArrayHelper',
                    ],

And this this works!

> {{ dump (array_helper.map(devices, 'id', 'name')) }}

Why? What if I don't want to define a global but an "use" in my view? 

| Q                | A
| ---------------- | ---
| Yii vesion      |2.07
| PHP version      |7.04
| Operating system |Arch

**Comment by summerknight** [comment]
As I know 'use' feature is only for widgets.

http://www.yiiframework.com/doc-2.0/guide-tutorial-template-engines.html#additional-configuration
https://github.com/yiisoft/yii2/issues/6604

**Comment by summerknight** [comment]
@samdark I think it is necessary to describe this feature more obviously in Yii2 twig docs. Or already done? Sorry if so

**Comment by samdark** [comment]
@summerknight would be great if you'll add docs about it. I'm totally busy with core :(

**Comment by summerknight** [comment]
@samdark pull request is created. @seisvalt thanks for the issue
