### ISSUE TITLE
url() and path() seem to be broken

### ISSUE THREAD

**Issue by Kolyunya** [yiisoft/yii2-twig#59]
~~~php
    public function path($path, $args = [])
    {
        if ($args !== []) {
            $path = array_merge([$path], $args);
        }
        return Url::to($path);
    }

    public function url($path, $args = [])
    {
        if ($args !== []) {
            $path = array_merge([$path], $args);
        }
        return Url::to($path, true);
    }
~~~

Both functions pass `paths` to `Url::to` as a strings when no arguments are provided. This results in original `paths` being returned instead of URLs being created by `Url::to`.

**Comment by samdark** [comment]
https://github.com/yiisoft/yii2-twig/pull/46?

**Comment by Kolyunya** [comment]
@samdark thanks!

#46 make function behavior over-complicated and inconsistent:
* When we want to create an URL from path with parameters we can pass it (path) as a string like this: `url('foo/bar', {baz: quux})`.
* But when we want to create an URL from path without parameters we *must* wrap it in an array: `url(['foo/bar'})`.

I think that those functions should always get `path` as a string.

**Comment by samdark** [comment]
> What could be the use-case of passing a regular string to Url::to without parameters?

Quoting docs:

- a string with a leading `@`: it is treated as an alias, and the corresponding aliased string
will be returned.
- an empty string: the currently requested URL will be returned;
- a normal string: it will be returned as is.

**Comment by Kolyunya** [comment]
@samdark thanks. I missed that point. Hope we can fix this issue soon.

**Comment by samdark** [comment]
So do you think #46 is OK?

**Comment by Kolyunya** [comment]
@samdark yes, I think it is impossible to create a better wrapper around `Url::to` without functionality loss. Do I get it right that the whole point of those functions is to overcome the limitations of twig's array syntax which won't allow us to call `Url::to` directly?
