### ISSUE TITLE
A lean fork

### ISSUE THREAD

**Issue by U-D13** [yiisoft/yii2-twig#64]
I have [forked] this repo for research purposes and cleaned up the history quite a bit. All committer and tag information has been preserved.

At the time of writing this repo has 4661 commits (9.66 MiB), my fork — 139 (111.39 KiB). I would recommend doing a `master` and tags reset here.

[forked]: //github.com/U-D13/yii2-twig

**Comment by samdark** [comment]
I see no sense in doing that. We'd like to keep what we have.

**Comment by U-D13** [comment]
All right, sure, go ahead and keep all the of the rest of Yii2 history (4500+ commits, that have nothing to do with this extension) along with those just 139 specific to the extension. :) I was just offering a little (c)leaner version, without all the completely unrelated stuff.

**Comment by samdark** [comment]
It's not completely unrelated. The extension was part of framework so many commits made are about extension as well. Also, changing sha1 hash of commits is a bad idea if repository is used publicly because people may refer specific commit.

**Comment by U-D13** [comment]
I can not disagree about hashes — those are undoubtedly important. That, in my opinion, is the only sensible reason why retain the status quo.

But there are only exactly 10 commits of those 4500+ that deal with the respective subtree (`extensions/yii/twig/`) before everything else got removed in this timeline. The rest of that crud is just crud in the context of this particular extension. The same applies to the [Smarty extension], with the nuance that there's even less commits that are common with the rest of timeline of Yii 2 — just 4. Therefore your argument (namely "[..] many commits made are about extension as well") is invalid. :slightly_smiling_face:

[Smarty extension]: //github.com/yiisoft/yii2-smarty
