### ISSUE TITLE
Tag a release

### ISSUE THREAD

**Issue by schmunk42** [yiisoft/yii2-twig#73]
### What steps will reproduce the problem?

Install stable version, and use url-syntax from docs, like so:

```
{{ url(['/mycontroller2/myaction2'], {'myparam':123}) }}
```

### What's expected?

A rendered page

### What do you get instead?

```
Twig_Error_Runtime

An exception has been thrown during the rendering of a template ("Array to string conversion").
```

![bildschirmfoto 2017-03-25 um 16 02 42](https://cloud.githubusercontent.com/assets/649031/24323356/a514ad2a-1174-11e7-9b16-91209bc2c310.png)

This commit 37c0e3952059ea895d88b92967415513e44f88b0 fixes this.

### Additional info

| Q                | A
| ---------------- | ---
| Yii version       | 2.0.11 (Twig 2.0.6)
| PHP version      | 7.1
| Operating system | Linux (Docker)

**Comment by samdark** [comment]
On it.

**Comment by schmunk42** [comment]
Nice, thank you.

Tests failed on PHP 7, btw. But looks like a `phpunit` issue.
