### ISSUE TITLE
Enh #43 Break compatibility?

### ISSUE THREAD

**Issue by Insolita** [yiisoft/yii2-twig#74]
### What steps will reproduce the problem?
After upgrade to 2.1.0, the  twig globals configuration stopped working as expected
```php
   'globals'=>[
       'html'=>'\yii\helpers\Html'
       ... etc
  ]
```
### What's expected?
  it should be work, or throw exception about not-supported syntax
### What do you get instead?
all  usages of aliases declared in globals silently skipped and do nothing 
after change configuration like as
```php
   'globals'=>[
       'html'=>['class'=>'\yii\helpers\Html']
       ... etc
  ]
```
Everything began to work as before upgrade

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       |2,0,11
| PHP version      |7,1,3
| Operating system | Arch

**Comment by samdark** [comment]
That's expected and is why release is tagged with 2.1 instead of 2.0.

**Comment by Insolita** [comment]
well, but there is not a single mention of it - neither in the changelog, nor in the documentation, nor in the PR release

**Comment by samdark** [comment]
Yes. That's bad... seems I forgot it :(

**Comment by samdark** [comment]
> This version is not fully backwards compatible with 2.0.6.

**Comment by samdark** [comment]
But I guess and UPGRADE document is needed...
