### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by Sampa** [yiisoft/yii2-twig#76]
### What steps will reproduce the problem?
Doc: https://github.com/yiisoft/yii2-twig/blob/master/docs/guide/template-syntax.md
<a href="{{ url(['blog/view'], {'alias' : post.alias}) }}">{{ post.title }}</a>
Gives array to string conversion error

### Additional info
Simple putting blog/view as a string works.
<a href="{{ url('article/update', {'id': model.id}) }}">{{ t('Update') }}</a>

Just thought I should let you know=)

**Comment by samdark** [comment]
There's no error in docs. Added a test that verified that: https://github.com/yiisoft/yii2-twig/commit/aaec9444a666af98bf0b070d46f07744a333f59f
