### ISSUE TITLE
Error in docs in Template Syntax -> URLs

### ISSUE THREAD

**Issue by Aleksey203** [yiisoft/yii2-twig#88]
### What steps will reproduce the problem?
Need to read https://github.com/yiisoft/yii2-twig/blob/master/docs/guide/template-syntax.md 
Chapter URLs

### What's expected?
`<a href="{{ path(['blog/view'], {'alias' : post.alias}) }}">{{ post.title }}</a>
<a href="{{ url(['blog/view'], {'alias' : post.alias}) }}">{{ post.title }}</a>`
it`s not correct

### What do you get instead?

Correct is
`<a href="{{ path('blog/view', {'alias' : post.alias}) }}">{{ post.title }}</a>
<a href="{{ url('blog/view', {'alias' : post.alias}) }}">{{ post.title }}</a>`
without [ ]

### Additional info

| Q                | A
| ---------------- | ---
| Yii vesion       | 2.0.12
| PHP version      | 5.6.30
| Operating system | ubuntu 14.04

**Comment by schmunk42** [comment]
Which version of yii2-twig do you have?
Should be fixed in 2.1.0, if this is a duplicate: https://github.com/yiisoft/yii2-twig/issues/73

**Comment by samdark** [comment]
Yes, it should be fixed...
