### ISSUE TITLE
UPGRADE for PHP 7 and Twig 2

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii2-twig#92]
Need UPGRADE notes.

**Comment by cebe** [comment]
also specify php version requirement in the readme.

**Comment by amarox** [comment]
@samdark why 2.2.0? Maybe 2.1.2?

**Comment by samdark** [comment]
No since it breaks compatibility.

**Comment by amarox** [comment]
Twig2 already in use since 2.1.1. And twig2 requirement php7. For this issue need to add only upgrade notes. Right? Compatibility will not be affected.

**Comment by amarox** [comment]
I made a mistake. Upgrade to Twig 2 in master branch
